# Wrangler TOML configuration for hono-template
name = "hono-template"
main = "src/index.ts"
compatibility_date = "2026-02-08"

# Uncomment and configure the following sections as needed:
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
