# Wrangler TOML configuration for hono-template
name = "hono-template"
compatibility_date = "2026-02-08"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
minify = true

# Required for Sentry integration
version_metadata = { binding = "CF_VERSION_METADATA" }

# [Optional] Enable source map uploading for better error tracking in Sentry
# Make sure you run `npx @sentry/wizard@latest -i sourcemaps` to set up Sentry source map uploading
# upload_source_maps = true

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
